# Generated by Django 5.2 on 2025-06-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Brand of the service', max_length=50)),
                ('model', models.CharField(help_text='Model type', max_length=50)),
                ('type', models.CharField(help_text='Service type category', max_length=50)),
                ('product_name', models.CharField(help_text='Name of the service product', max_length=100)),
                ('before_price', models.DecimalField(decimal_places=2, help_text='Price before discount', max_digits=10)),
                ('after_price', models.DecimalField(decimal_places=2, help_text='Price after discount', max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special discounted price', max_digits=10, null=True)),
                ('link', models.URLField(blank=True, help_text='URL link for more details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Price',
                'verbose_name_plural': 'Service Prices',
                'ordering': ['brand', 'model', 'type', 'product_name'],
                'unique_together': {('brand', 'model', 'type', 'product_name')},
            },
        ),
    ]
