# Generated by Django 5.2 on 2025-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_servicecategory_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pagedetails',
            field=models.TextField(blank=True),
        ),
    ]
